"""rename address

Revision ID: 4207aadb7091
Revises: 3e690d770078
Create Date: 2024-04-03 17:15:17.081137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4207aadb7091'
down_revision = '3e690d770078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
